### ISSUE TITLE
reflux-state-mixin: Unable to use Immutable.js in state.

### ISSUE THREAD

**Issue by ghost** [yonatanmn/reflux-state-mixin#10]
Hello.

Using Map, List or other data structures from the [immutable.js](https://facebook.github.io/immutable-js/) library will result in error:

``` cjsx
Reflux = require 'reflux'
StateMixin = require 'reflux-state-mixin'
{UserActions} = require 'actions'
{Map} = require 'immutable'

UserStore = Reflux.createStore

    listenables: [UserActions]
    mixins: [StateMixin.store]

    getInitialState: ->
        users: Map()

###
in console:
Uncaught TypeError: Property description must be an object: undefined
###
```

**Comment by yonatanmn** [comment]
fixed it, i'll upload correction in the next days.
for the mean time - 
in your npm folder, reflux-state-mixin/lib/storeMixin, find: 

```
  this[actionName] = Reflux.createAction(options);
// change to:
  this[actionName] = Reflux.createAction();

```

this will solve the problem for now

**Comment by ghost** [comment]
Yes :+1: I examined the source and was like "why would you pass the state value as option to action creator" 

Thanks

**Comment by yonatanmn** [comment]
[fixed](https://github.com/yonatanmn/Super-Simple-Flux/commit/28855e925140c02f0636e7dbbb5fcc2d2cc45e94), thx
