### ISSUE TITLE
Implicit creation of action on state property throws "TypeError: Attempting to change configurable attribute of unconfigurable property."

### ISSUE THREAD

**Issue by databu** [yonatanmn/reflux-state-mixin#12]
When a store is initialised, actions on properties in the initial state are automatically created in storeMixin.init(): attachAction is called with the state property as the options parameter, which is then interpreted in Reflux.createAction() as the action definition. It is therefore used to extend the action Functor later in that function. This doesn't work if the state property is an object which has itself properties which collide with already-existing properties of the functor, e.g. "name".

Example store that fails:

```
import Reflux from "reflux";
import { store as StoreState} from "reflux-state-mixin";

export default Reflux.createStore({
    mixins: [StoreState],

    getInitialState() {
        return {problem: {name: "This doesn't work"}};
    }
});
```

**Comment by yonatanmn** [comment]
Not sure if I understand what fails. 
Iv'e tried this code and it work's as expected for me.

expected = there should be a state in the store called `problem` which is initially an object with `name` property, so I can use it in a component like so:

``` js
@connector(testStore, 'problem')
class test extends React.Component {
 render() {
  return (
        <div>{this.state.problem && this.state.problem.name}</div>
    )
}
}
```

I cannot connect to `name` which is not a **`state`** - just part of an object.

**Comment by databu** [comment]
Not using Flux anymore and Flux seems to be abandoned anyway, so closing this.
