### ISSUE TITLE
enhancement: this.setState like react's

### ISSUE THREAD

**Issue by erzzo** [yonatanmn/reflux-state-mixin#13]
In react is this

```
this.setState(users);
```

equal to

```
this.setState({
  users: users
});
```

**Comment by yonatanmn** [comment]
hey @erzzo . first take a look at [cartiv](https://github.com/yonatanmn/Cartiv), it's the new library for super-simple-flux architecture. 
Secondly - this is just JS - so 
`users !== {users: users}`
but, in [es6](https://babeljs.io/docs/learn-es2015/)
`{users} === {users: users}`
so you can do: 
`setState({users})`.

Hope this answers your question

**Comment by erzzo** [comment]
oh, sorry I forgot the parentheses... :+1:
