### ISSUE TITLE
Trigger is not fired

### ISSUE THREAD

**Issue by erzzo** [yonatanmn/reflux-state-mixin#14]
Hi, when I use this mixin this way:

```
onTestCompleted: ({data}) ->
    state = _.set this.state, 'nestedObject.data', data
    this.setState state
```

it will not trigger the action in component using the connect function. Can you help me?

**Comment by yonatanmn** [comment]
I guess this is typeScript. not that familiar with syntax, can you provide JS version ?

**Comment by erzzo** [comment]
it's coffeescript, sorry for that.
And it uses https://lodash.com/docs#set to change the existing object's property

```
  onTestCompleted: function(data) {
    state = _.set(this.state, 'nestedObject.data', data);
    return this.setState(state);
  }
```

**Comment by yonatanmn** [comment]
lodash doc: `Note: This method mutates object.`
you should treat this.state as immutable. (same as reactClass.state)
