### ISSUE TITLE
state property and action can't have the same name

### ISSUE THREAD

**Issue by kriscarle** [yonatanmn/reflux-state-mixin#6]
I had an action called "show" and a boolean property "show" and get an error because it is attempting to call trigger() on the listener function for my "show" action. I think this is because statemixin automatically creates actions that trigger back to the components connected to the store. Would it work to wrap those actions in an object? For example on line 24:

```
 this.stateActions[actionName] = Reflux.createAction(options);
```

instead of 

```
 this[actionName] = Reflux.createAction(options);
```

The work around is to use more descriptive (and different) names for actions and values, but it wasn't immediately obvious from the error message that this was the problem.

**Comment by yonatanmn** [comment]
Hey, please see this PR, and my reply: https://github.com/yonatanmn/reflux-state-mixin/pull/3

Maybe we can change the API to be something like this:

``` js
   componentDidMount: function(){
        this.listenTo(AnimalStore, 'dogs', this.updateDogs); 
        // currently:    this.listenTo(AnimalStore.dogs,this.updateDogs); 
    },
```

**Comment by kriscarle** [comment]
Ah, I didn't notice that PR.  You are right that it breaks convention with reflux, so that would probably require extending ListenerMixin? Maybe this would be better? In my PR I called it "stateActions" but maybe calling it "updates" avoids confusion with the actions chosen by the user?

``` javascript
componentDidMount: function(){
        this.listenTo(AnimalStore.updates.dogs, this.updateDogs); 
        // currently:    this.listenTo(AnimalStore.dogs,this.updateDogs); 
    },
```

Not a big deal either way, maybe just a note in the README would be enough in case anyone else runs into is. 
Thanks!
